# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_coupon_used',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
