# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20161027_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
