# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_auto_20161023_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='profiles',
        ),
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
