# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_auto_20161027_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='name',
        ),
    ]
