# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_auto_20161027_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
