# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='/Users/maxleone/repos/shoppingcarthero/shoppingcarthero/media/item_images/None/no-img.jpg/', upload_to='/Users/maxleone/repos/shoppingcarthero/shoppingcarthero/media/item_images/'),
        ),
    ]
