# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20160903_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'Freshman'), ('SHP', 'Sophomore')], default='USD', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='details',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='items/no_image.png', upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
