# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20160903_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
