# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20160903_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='details',
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('SHP', 'SHP')], default='USD', max_length=3),
        ),
    ]
