# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20160924_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='short',
            field=models.TextField(blank=True, default=''),
        ),
    ]
