# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_item_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShopProfile',
        ),
    ]
